import { parse as parseYaml } from "yaml";
import { collectorSchema, controlSchema } from "./schema.js";
import type { CollectorDefinition, ControlDefinition } from "./types.js";
import { validatePreparationCommand, validateReadOnlyCommand } from "./safety.js";

/**
 * Validate a standalone catalog YAML document (as authored by an operator or
 * generated by an agent). The document may contain `controls:` and/or
 * `collectors:` lists. Used by the CLI (`controls add`) and the MCP
 * `catalog_add_custom_control` tool before anything is written to the custom
 * catalog directory.
 */
export interface CustomDocumentResult {
  controls: ControlDefinition[];
  collectors: CollectorDefinition[];
  errors: string[];
}

export function validateCatalogDocument(
  yamlText: string,
  knownCollectors: Map<string, CollectorDefinition>,
): CustomDocumentResult {
  const errors: string[] = [];
  let doc: any;
  try {
    doc = parseYaml(yamlText);
  } catch (error) {
    return {
      controls: [],
      collectors: [],
      errors: [`YAML parse error: ${(error as Error).message}`],
    };
  }
  if (!doc || typeof doc !== "object") {
    return {
      controls: [],
      collectors: [],
      errors: ["document must contain controls: and/or collectors: lists"],
    };
  }

  const collectors: CollectorDefinition[] = [];
  for (const entry of doc.collectors ?? []) {
    const parsed = collectorSchema.safeParse(entry);
    if (!parsed.success) {
      errors.push(
        `collector ${entry?.id ?? "?"}: ${parsed.error.issues.map((i) => `${i.path.join(".")} ${i.message}`).join("; ")}`,
      );
      continue;
    }
    const safety = validateReadOnlyCommand(parsed.data.command);
    if (!safety.safe) {
      errors.push(`collector ${parsed.data.id}: unsafe command — ${safety.reason}`);
      continue;
    }
    if (parsed.data.prepareCommand) {
      const prepSafety = validatePreparationCommand(parsed.data.prepareCommand);
      if (!prepSafety.safe) {
        errors.push(`collector ${parsed.data.id}: unsafe prepare command — ${prepSafety.reason}`);
        continue;
      }
    }
    collectors.push(parsed.data as CollectorDefinition);
  }

  const available = new Map(knownCollectors);
  for (const collector of collectors) available.set(collector.id, collector);

  const controls: ControlDefinition[] = [];
  for (const entry of doc.controls ?? []) {
    const parsed = controlSchema.safeParse(entry);
    if (!parsed.success) {
      errors.push(
        `control ${entry?.id ?? "?"}: ${parsed.error.issues.map((i) => `${i.path.join(".")} ${i.message}`).join("; ")}`,
      );
      continue;
    }
    const control = parsed.data as unknown as ControlDefinition;
    if (!available.has(control.collector)) {
      errors.push(
        `control ${control.id}: unknown collector ${control.collector} (define it in this document or use an existing one)`,
      );
      continue;
    }
    controls.push(control);
  }

  if (controls.length === 0 && collectors.length === 0 && errors.length === 0) {
    errors.push("document contains no controls or collectors");
  }
  return { controls, collectors, errors };
}

/** YAML template for a custom control, ready for an operator or agent to fill in. */
export function controlTemplate(options: {
  provider: "aws" | "azure" | "gcp";
  collectorId?: string;
}): string {
  const providerUpper = options.provider.toUpperCase();
  return `# CloudRanger custom control. Validate with: cloudranger controls add <file>
# Reference: existing controls in packages/catalog/catalog/controls/.
controls:
  - id: CUSTOM-${providerUpper}-MYSERVICE-001   # (CR|CUSTOM)-(AWS|AZURE|GCP)-<SERVICE>-<NNN>
    version: 1.0.0
    provider: ${options.provider}
    service: myservice
    title: One-line statement of the desired state
    description: What this control verifies, in one or two sentences.
    rationale: Why failing this matters — the realistic risk.
    severity: medium            # informational | low | medium | high | critical
    categories: [custom]
    source:
      engine: custom            # keep "custom" for your own controls
      id: my-org-policy-reference
      license: Apache-2.0
    collector: ${options.collectorId ?? `${options.provider}.myservice.my_collector  # existing collector id, or define one below`}
    # For collectors returning an object with an array: path to that array.
    # Use "$" when the output root is the array (az/gcloud list) or a single
    # account-level object. Omit for per_resource collectors.
    resourcesPath: $
    resourceIdField: name       # field identifying the resource ($resourceKey for per_resource)
    # applicableWhen:           # optional scoping expression (same ops as passWhen)
    passWhen:                   # expression ops: equals, notEquals, exists, notExists,
      op: equals                # in, notIn, contains, startsWith, endsWith, gt/gte/lt/lte,
      path: someField           # daysSinceGt/Lt, matches, lengthEquals/Gt, isEmpty,
      value: true               # isPublicCidr, portIncludes, portStringIncludes,
                                # and/or/not, anyItem/allItems/noneItem
    # onError:                  # optional: map CLI errors to outcomes
    #   - contains: NotFoundException
    #     status: fail
    failMessage: Resource does not meet the desired state.
    passMessage: Resource meets the desired state.
    remediation:
      summary: How the operator fixes it.
      steps:
        - Step one (operator action; CloudRanger never executes changes).
      verifyCommand: ${options.provider === "aws" ? "aws myservice describe-things --region <region> --output json" : options.provider === "azure" ? "az myservice list --output json" : "gcloud myservice list --project <project> --format json"}
    compliance: []
    references:
      - https://example.com/internal-policy

# Optional: define a new read-only collector this control needs.
# collectors:
#   - id: ${options.provider}.myservice.my_collector
#     provider: ${options.provider}
#     service: myservice
#     description: What this collects.
#     kind: single              # single | per_resource
#     command: ${options.provider === "aws" ? "aws myservice describe-things --region {region} --output json" : options.provider === "azure" ? "az myservice list --output json" : "gcloud myservice list --project {project} --format json"}
#     regional: ${options.provider === "aws"}
#     outputFormat: json
`;
}
